eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#name:
#  value: customer

spring:
  cloud:
    config:
      override-system-properties: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true