eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

name:
  value: jsl-group

spring:
  cloud:
    config:
      override-system-properties: false


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true