server:
  port: 8072
spring:
  data:
    mongodb:
      username: username
      password: password
      host: mongo_db
      port: 27017
      database: customer
#      authentication-database: admin